server:
  port: 8080

spring:
  application:
    name: event-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/event_manager
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret-key: 9f3c8b2a1d4e7f6a5c8d0e2b9a4f6c7d1e8b3a5f0c9d2e6a7b4f8c1d5e
  lifetime: 86400000

logging:
  level:
    root: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /index.html
    url: /event-manager-openapi.yaml

event:
  status:
    cron: "0 */5 * * * *"